[package]
name = "cattenx"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.0", features = ["fs", "io-util", "macros", "net", "rt-multi-thread"] }
toml = "0.8.14"
